name: "takuya-xoauth2"

on:
  push:
    branch:
      - master
    paths:
      - 'lib/**'
      - '*.gemspec'
      - '.github/workflows/actions.yml'

jobs:
  run-bundle-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundle-cache: false
          ruby-version: 3.1
