name: "takuya-xoauth2"

on:
  push:
    branch:
      - master
    paths:
      - 'lib/**'
      - '*.gemspec'
      - '.github/workflows/actions.yml'

jobs:
  test-GMail-API-xoauth2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run : |
          apt-get update && apt-get -y install jq
      - run : |
          echo 環境変数のメモ
          echo expected variables
          echo Google-GCP-OAUTH2-client
          ${{ secrets.CLIENT_SECRET_JSON }} >>  credentials/client_secret.json
          ${{ secrets.TOKENS_YAML }} >>  credentials/client_secret.json
          cat credentials/client_secret.json | jq '.web | {"project":.project_id,"client": .client_id}'
          ruby -r yaml -e 'puts YAML.load_file("credentials/tokens.yaml").to_a[0][1]' | jq .
      - uses: ruby/setup-ruby@v1
        with:
          bundle-cache: false
          ruby-version: 3.1
      - run: |
          bundle install
          bundle exec rspec spec/
          
      

