name: "bundle install"

on:
  push:
    branch:
      - master
    paths:
      - 'lib/**'
      - '*.gemspec'
      - '.github/workflows/actions.yml'

jobs:
  run-bundle-install:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: 3.1
      - run: |
          [ -e work ] && rm -rf work
          mkdir work && cd work
          bundle init
          URL=https://github.com/takuya/ruby-google-xoauth2.git
          echo "gem 'takuya-xoauth2', git: '$URL'" >> Gemfile
          bundle install

